### ISSUE TITLE
Requests after onLoad are not present in HAR

### ISSUE THREAD

**Issue by andydavies** [cyrus-and/chrome-har-capturer#10]
I haven't checked what happens for events that start before onload and complete after, but certainly events that start and finish after onload are missing from the generated HAR file.

To check for completeness you'll probably need a timeout period in which you watch for network requests and if none occur within the timeout period decide the page is complete.

**Comment by cconcolato** [comment]
I have the same use cases and I don't want to modify my application to measure it. I don't see an ideal solution but recording until some timeout after the last network activity or after the page load isn't so bad if properly documented.
