### ISSUE TITLE
Multiple URLs - Stop working

### ISSUE THREAD

**Issue by junaidahmed83** [cyrus-and/chrome-har-capturer#13]
I have noticed that when I supply multiple URLs, it keeps breaking after opening a couple of URLs. The behavior is not dependent on the particular URL. It works fine with single URL. Just that whenever I give a list of URLs, it opens some URLs and then breaks. Have you faced such issue while loading several URLs?

Moreover, sometimes it even gets stuck at one URL and would not move on further to the next URL, which might be due to the dependency on the onLoad event?

**Comment by cyrus-and** [comment]
@junaidahmed83 It should be fixed now. Any feedback will be greatly appreciated.
