### ISSUE TITLE
DNS flush only works after the second attempt

### ISSUE THREAD

**Issue by cyrus-and** [cyrus-and/chrome-har-capturer#15]
Example:

```
$ node bin/cli.js http://example.com 2> /dev/null | grep '"dns": '
                    "dns": 0,
$ node bin/cli.js http://example.com 2> /dev/null | grep '"dns": '
                    "dns": 28.9919999995618,
$ node bin/cli.js http://example.com 2> /dev/null | grep '"dns": '
                    "dns": 28.6919999998645,
$ node bin/cli.js http://example.com 2> /dev/null | grep '"dns": '
                    "dns": 28.49299999797947,
```

**Comment by svagi** [comment]
I'm running chrome with --enable-benchmarking and  --enable-net-benchmarking, It seems that DNS flush does not occur immediately after the request.

Example:
```sh
$ chrome-har-capturer http://example.com 2> /dev/null | grep '"dns": '
                    "dns": 53.57400001958008,
$ chrome-har-capturer http://example.com 2> /dev/null | grep '"dns": '
                    "dns": -1,
chrome-har-capturer http://example.com 2> /dev/null | grep '"dns": '
                    "dns": -1,
# After some time (~1min)
$ chrome-har-capturer http://example.com 2> /dev/null | grep '"dns": '
                    "dns": 54.88599999807773,
```
I'm not sure if it's more chrome related or not.

**Comment by cyrus-and** [comment]
Thanks for sharing your output. Still I experience the behavior that I reported; clearly this thing is not reliable...

[Here][1]'s how DevTools compute that value, and I'm doing the same, so I thing it's an issue with Chrome. It might be worthy to file an [issue][2] against Chromium.

[1]: https://chromium.googlesource.com/chromium/blink.git/+/8d2d7506bebf376fcb885f8344e1df38de2998f2/Source/devtools/front_end/sdk/HAREntry.js#153
[2]: https://bugs.chromium.org/p/chromium/issues/list
