### ISSUE TITLE
There is no content in HAR file

### ISSUE THREAD

**Issue by aliraza0337** [cyrus-and/chrome-har-capturer#17]
When we use the network tool we can save the HAR file with content as well(that saves the data for each request with encoding scheme as well). I think if you can add that feature as well it will make it more useful.

**Comment by cyrus-and** [comment]
Hi Ali, this is a planned feature, stay tuned.

**Comment by cyrus-and** [comment]
I rolled out the feature, if you could test it a bit and provide me some feedback it would be great!
