### ISSUE TITLE
error : connect ECONNREFUSED

### ISSUE THREAD

**Issue by ScottCoats** [cyrus-and/chrome-har-capturer#20]
when i tried ti run chrome-har-capturer -o out.har https://github.com

it returns 

cannot connect to chrome
error : connect ECONNREFUSED

i'm on  centos(64)

**Comment by cyrus-and** [comment]
Some questions.

Which version of Chrome?

Did you start Chrome with the following options?

    google-chrome --remote-debugging-port=9222 \
                  --enable-benchmarking \
                  --enable-net-benchmarking

Are you able to load `http://127.0.0.1:9222/` with some browser?

What is the output of: `lsof -n -i :9222`?

**Comment by ScottCoats** [comment]
i have new stable version and yes i did apply those options. output of: lsof -n -i :9222 is empty. 'curl http://127.0.0.1:9222/' is couldn't connect to host.

**Comment by cyrus-and** [comment]
Well, it seems a problem with Chrome itself. Anyway, can you be more specific about the version? Take it from `chrome://version/`.
