### ISSUE TITLE
Set User Agent?

### ISSUE THREAD

**Issue by JamshedVesuna** [cyrus-and/chrome-har-capturer#22]
In [Chromium's Telemetry](https://catapult.gsrc.io/telemetry), it's possible to [set the user agent](https://code.google.com/p/chromium/codesearch#chromium/src/tools/telemetry/telemetry/internal/browser/user_agent.py&q=user%20agent%20file:%5Esrc/&sq=package:chromium&l=1), is there a way to do that with this package without having to directly edit the page set / story? 

Thanks!

**Comment by cyrus-and** [comment]
Yes, now it is. I've just added the [`userAgent` option](/cyrus-and/chrome-har-capturer#loadurls-options) (and the corresponding [`--agent` flag](/cyrus-and/chrome-har-capturer#use-the-bundled-utility)).
