### ISSUE TITLE
Not working...

### ISSUE THREAD

**Issue by msjuck** [cyrus-and/chrome-har-capturer#23]
I can't open with "--enable-net-benchmarking --enable-benchmarking" option on my phone!

Android Chrome does not run with this option.

I think turning off DNS clear function...

any ideas?

> choi_teemo:WEB_CE choi$ chrome-har-capturer naver.com
Cannot connect to Chrome
Error: Cannot inject JavaScript: {
    "result": {
        "type": "object",
        "objectId": "{\"injectedScriptId\":1,\"id\":1}",
        "subtype": "error",
        "className": "TypeError",
        "description": "TypeError: Cannot read property 'clearCache' of undefined\n    at <anonymous>:1:20\n    at Object.InjectedScript._evaluateOn (<anonymous>:875:140)\n    at Object.InjectedScript._evaluateAndWrap (<anonymous>:808:34)\n    at Object.InjectedScript.evaluate (<anonymous>:664:21)"
    },
    "wasThrown": true,
    "exceptionDetails": {
        "text": "Uncaught TypeError: Cannot read property 'clearCache' of undefined",
        "url": "",
        "line": 1,
        "column": 19,
        "scriptId": "51"
    }
}

`

**Comment by msjuck** [comment]
oi_teemo:WEB_CE choi$ sudo npm install -g chrome-har-capturer
Password:
/usr/local/bin/chrome-har-capturer -> /usr/local/lib/node_modules/chrome-har-capturer/bin/cli.js

> bufferutil@1.2.1 install /usr/local/lib/node_modules/chrome-har-capturer/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node

> utf-8-validate@1.2.1 install /usr/local/lib/node_modules/chrome-har-capturer/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
/usr/local/lib
└─┬ chrome-har-capturer@0.5.0 
  ├─┬ chrome-remote-interface@0.11.0 
  │ ├── commander@2.1.0 
  │ └─┬ ws@0.8.1 
  │   ├─┬ bufferutil@1.2.1 
  │   │ ├── bindings@1.2.1 
  │   │ └── nan@2.2.0 
  │   ├── options@0.0.6 
  │   ├── ultron@1.0.2 
  │   └── utf-8-validate@1.2.1 
  ├── colors@1.1.2 
  └─┬ commander@2.9.0 
    └── graceful-readlink@1.0.1 

choi_teemo:WEB_CE choi$ chrome-har-capturer naver.com
Cannot connect to Chrome
Error: Cannot inject JavaScript: {
    "result": {
        "type": "object",
        "objectId": "{\"injectedScriptId\":1,\"id\":1}",
        "subtype": "error",
        "className": "TypeError",
        "description": "TypeError: Cannot read property 'clearCache' of undefined\n    at <anonymous>:1:20\n    at Object.InjectedScript._evaluateOn (<anonymous>:875:140)\n    at Object.InjectedScript._evaluateAndWrap (<anonymous>:808:34)\n    at Object.InjectedScript.evaluate (<anonymous>:664:21)"
    },
    "wasThrown": true,
    "exceptionDetails": {
        "text": "Uncaught TypeError: Cannot read property 'clearCache' of undefined",
        "url": "",
        "line": 1,
        "column": 19,
        "scriptId": "49"
    }
}
choi_teemo:WEB_CE choi$

**Comment by msjuck** [comment]
I can't open with "--enable-net-benchmarking --enable-benchmarking"

Android Chrome does not run with this option.

**Comment by cyrus-and** [comment]
Can you please tell me more about your configuration?
Are you trying to run chrome-har-capturer on your PC to inspect Chrome on your Android phone which is connected via an USB cable?

**Comment by cyrus-and** [comment]
Well it looks like that was the case... You can now run chrome-har-capturer with the `-f` option (or with `options.force = true`) to ignore such errors, but please note that in this way the DNS cache and socket pool are not flushed.
