### ISSUE TITLE
where or how to use remote debugging host

### ISSUE THREAD

**Issue by c0b** [cyrus-and/chrome-har-capturer#24]
although this claims to be supporting a different host other than `localhost`, but how does it support that? from chrome command line I only see `google-chrome --remote-debugging-port=9222` to specify a port number but don't see how to specify a different listening host, that chrome will always listen on `localhost:9222` only, caused that remote debugging protocol never goes out of localhost `127.0.0.1`

```console
  -t, --host <host>    Remote Debugging Protocol host
```

**Comment by cyrus-and** [comment]
AFAIK that's not possible using Chrome itself. But I guess you can still add an `iptable` rule like [this](http://unix.stackexchange.com/q/111433); never tried though..
