### ISSUE TITLE
can this have a timeout option?

### ISSUE THREAD

**Issue by c0b** [cyrus-and/chrome-har-capturer#26]
for some reason, either server side slow or client side network congestion, some pages seemingly take for ever to fully load, in this case can we have a timeout option to give up? I have a PR if this feature is agreed useful

```console
Usage: chrome-har-capturer [options] URL...

Options:

  -h, --help           output usage information
  -t, --host <host>    Remote Debugging Protocol host
  -p, --port <port>    Remote Debugging Protocol port
  -o, --output <file>  dump to file instead of stdout
  -c, --content        also capture the requests body
  -a, --agent <agent>  user agent override
  -d, --delay <ms>     time to wait after the load event
      --timeout <seconds>  Wait at most how many seconds before giving up
  -f, --force          continue even without benchmarking extension
  -v, --verbose        enable verbose output on stderr
```

**Comment by c0b** [comment]
I mean the load API better to have a timeout option

https://github.com/cyrus-and/chrome-har-capturer#loadurls-options

**Comment by cyrus-and** [comment]
Yes I think this would be a useful addition. I'd suggest the names: `-g, --give-up` for the command line and `giveUpTimeout` for the API.

Anyway, next time it happens, try to check whether the page is actually not loading or chrome-har-capturer fails to detect the event.

**Comment by c0b** [comment]
:+1:
