### ISSUE TITLE
Capturing of HAR for youtube videos from chrome at the end of duration

### ISSUE THREAD

**Issue by vuyyala** [cyrus-and/chrome-har-capturer#28]
Hi all,
        Is there a way to capture HAR for a youtube video at the end of its duration?Through the following code it is capturing the HAR at the start of the video itself.What modifications need to be done if I don't know the duration in advance.

server=Server('path to browsermob-proxy')
server.start()
proxy=server.create_proxy()
from selenium import webdriver
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument("--proxy-server={0}".format(proxy.proxy))
browser = webdriver.Chrome(executable_path="/home/sivakesava/chromedriver",chrome_options = chrome_options)
proxy.new_har("CS")
browser.get("https://www.youtube.com/watch?v=NFQeItqTfZk")
har=proxy.har
print har
browser.quit()
server.stop()

**Comment by cyrus-and** [comment]
Well, the code you provided doesn't make use of this module so I cannot help you with it.

Yout best chance with chrome-har-capturer is to use an upper bound of the duration time of your videos with `--delay` or `onLoadDelay`.
