### ISSUE TITLE
Can't see requests whose response is redirect

### ISSUE THREAD

**Issue by marty90** [cyrus-and/chrome-har-capturer#30]
Hi,
thank you for the very useful script.
I've a little problem.
I noticed that in the HAR file are saved only requests whose response is 200 OK.
In particular I cannot see requests that lead to redirects, but I see only the second request for the page resulted from the redirect.
Is there a way to change this behavior?
Thank You

**Comment by cyrus-and** [comment]
You're welcome!

The [HAR spec][1] is not clear about that, it only defines a `redirectURL` field for `response`s objects. This module does just that: when an object comes from a HTTP redirect, the 200 OK response is saved and the `redirectURL` field is set accordingly.

In practice it should be possible to save the original request/response pair, but Chrome treats responses coming from a redirect in a special way, in particular it uses the same `requestId` for both the original and the redirect request. This complicates the implementation and poses new challenges, also considering that there may be more than one redirects.

I'll look into this, thanks for reporting. In the meanwhile you can resort to the `redirectURL` field if that's enough for you.

[1]: http://www.softwareishard.com/blog/har-12-spec/

**Comment by cyrus-and** [comment]
Here, I pushed a [candidate fix][1] in a separate branch, it should work (tested with [http.bin][2], `/redirect/:n`) but it would be great if you could give it a try.

I'm not entirely convinced that this is the expected behavior though... if you find some reference material please post it here.

Thanks.

[1]: https://github.com/cyrus-and/chrome-har-capturer/tree/redirects
[2]: https://httpbin.org/

**Comment by cyrus-and** [comment]
Well, it seems that this is what Chrome DevTools does when you "Copy All as HAR" from the menu.

**Comment by marty90** [comment]
Thank You so much for the quick response! It appears to work fine. Anyway I'll test it and let you know if there is any issue!

**Comment by cyrus-and** [comment]
Merged the fix in [0.9.0][1].

[1]: https://github.com/cyrus-and/chrome-har-capturer/releases/tag/v0.9.0
