### ISSUE TITLE
It hangs when an error with SSL/TLS certificate occurs 

### ISSUE THREAD

**Issue by svagi** [cyrus-and/chrome-har-capturer#33]
Hey @cyrus-and, another report.

Example:
```
$ curl https://www.facebook.cz/
curl: (51) SSL: no alternative certificate subject name matches target host name 'www.facebook.cz'


$ chrome-har-capturer https://www.facebook.cz/
...hangs...
 ```

If you try to enter URL in chrome, you will see a warning page. I guess that might be an issue?
Also `giveUpTime` option seems to have no effect in this case.

**Comment by cyrus-and** [comment]
Yep, it hangs because Chrome stops sending events through the WebSocket as it's waiting for an user action:

```
$ chrome-har-capturer -v https://www.facebook.cz/
# --- Start: https://www.facebook.cz/
# <-- Page.domContentEventFired: https://www.facebook.cz/
# <-- Page.interstitialShown: https://www.facebook.cz/
...hangs...
```

But using the `-g` option it does work to me:

```
$ chrome-har-capturer -v -g 3 https://www.facebook.cz/
# --- Start: https://www.facebook.cz/
# <-- Page.domContentEventFired: https://www.facebook.cz/
# --- Giving up: https://www.facebook.cz/
# --- End: https://www.facebook.cz/
FAIL https://www.facebook.cz/
{
    "log": {
        "version": "1.2",
        "creator": {
            "name": "Chrome HAR Capturer",
            "version": "0.9.0"
        },
        "pages": [],
        "entries": []
    }
}
```

**Comment by svagi** [comment]
It's working now, interesting... Restart of chrome helped. Anyway, thanks for the quick response!

**Comment by cyrus-and** [comment]
FYI a9e279afc1c590689fce6c6306e44c2d296a61c1 introduces the `--insecure` command line option to bypass certificates.

**Comment by rkoblev** [comment]
Could you add "insecure" option to API too?

**Comment by cyrus-and** [comment]
@rkoblev you can just use a `preHook` as shown in a9e279afc1c590689fce6c6306e44c2d296a61c1, hooks are part of the API.
