### ISSUE TITLE
Feature request: Load neutral page before closing connection

### ISSUE THREAD

**Issue by svagi** [cyrus-and/chrome-har-capturer#34]
**Feature**
Add default behavior or option for loading neutral page just before closing connection with the chrome.

**Reason**
The last loaded page is still open in the chrome (after HAR generation is complete) which may result in unnecessary CPU utilization of the chrome (it depends on the loaded page).

**Note**
I know It's possible to achieve this behavior with chrome-remote-interface, but I think it's better to use single connection, plus it's better to do this in one place (https://github.com/cyrus-and/chrome-har-capturer/blob/master/lib/client.js#L117). You can think of it as some kind of cleanup.

**Comment by cyrus-and** [comment]
It seems reasonable to make this the default behavior.

**Comment by svagi** [comment]
Great, thanks! 👍
