### ISSUE TITLE
Is there anyway to capture the parsed dom with this?

### ISSUE THREAD

**Issue by ravenbyron** [cyrus-and/chrome-har-capturer#35]
I would like to be able to save and use the parsed DOM is there any way to do this easily?

**Comment by cyrus-and** [comment]
You can use [chrome-remote-interface][1] directly (which is used by this module) to achieve that. It would be a bit more demanding as that module is basically a library.

For your specific use case you may want to take a look at the [DOM] module.

[1]: https://github.com/cyrus-and/chrome-remote-interface
[DOM]: https://chromedevtools.github.io/debugger-protocol-viewer/tot/DOM/

**Comment by ravenbyron** [comment]
thanks for the pointers...
