### ISSUE TITLE
Cannot connect to Chrome: Error: connect ECONNREFUSED 127.0.0.1:9222

### ISSUE THREAD

**Issue by sjfricke** [cyrus-and/chrome-har-capturer#36]
I keep getting this error and I have tried all the examples, the suggestions from the other issues pulled this is what I get

I am running it on Node 6.9.2 - Windows 10
also tried on Node 4.2.6 Ubuntu 16.04

Both get the same errors

**Comment by cyrus-and** [comment]
I have to ask, have you started Chrome with the `--remote-debugging-port=9222` option?

You can verify that with:

    curl http://localhost:9222/json

you can even load that URL with any browser, you should see a JSON array.

**Comment by sjfricke** [comment]
So the issue is when I try to SSH to the machine I get errors that `Gtx: cannot open display:`

If I am on it physically all works as expected

**Comment by cyrus-and** [comment]
Chrome cannot start without X (on Linux), options are:

- forward the X connection with `ssh -X`;
- use a fake X frame buffer: Xvfb;
- use the brand new `--headless` option (since version 58 I think)-

**Comment by cyrus-and** [comment]
I'm closing this as I think I clarified your issue. Feel free to reopen it if needed.

**Comment by sjfricke** [comment]
Hey, so it worked, I finally got the X Frame buffer to work

Thanks again!
