### ISSUE TITLE
Unable to run chrome-har-capturer

### ISSUE THREAD

**Issue by SivaKesava1** [cyrus-and/chrome-har-capturer#37]
I installed with the command:
sudo npm install -g chrome-har-capturer
 but when I run 
google-chrome --remote-debugging-port=9222 \
              --enable-benchmarking \
              --enable-net-benchmarking
chrome-har-capturer -o out.har \
    https://github.com

I am getting this in the terminal and it is stopping:
/usr/bin/env: ‘node’: No such file or directory

Please suggest what has to be done.

**Comment by cyrus-and** [comment]
Do you have Node.js properly installed? Check with:

    node --version

**Comment by SivaKesava1** [comment]
No, I will check with Node.js installed.

**Comment by hansfilipelo** [comment]
In case you have installed node through package repositories in Debian / Ubuntu it is installed as `nodejs`, but many node apps (stupidly) assumes the node binary is called `node`. 

The work around is to symlink nodejs -> node (preferably under /usr/local): 

```
sudo ln -s /usr/bin/nodejs /usr/local/bin/node
```

**Comment by cyrus-and** [comment]
> but many node apps (stupidly) assumes the node binary is called node

@hansfilipelo what would be a non-stupid assumption then? The `nodejs-legacy` Debian/Ubuntu package exists to fix this.

> It should be noted that chrome-har-capturer requires node version >= 6

Wrong, it requires Node.js >= 4.

**Comment by hansfilipelo** [comment]
@cyrus-and Did not know that. Thanks!

Hmm... I got an error running chrome-har-capturer on one of my devices when using v4, which seemed to be a version incompatibility issue. I see now that my other device works perfectly fine with node v 4. 

Sorry to have caused confusion!
