### ISSUE TITLE
Not an Issue. A doubt.

### ISSUE THREAD

**Issue by SivaKesava1** [cyrus-and/chrome-har-capturer#39]
If I use a bandwidth shaper like netem to limit the bandwidth to different rates will this have any effect on this module? I mean how does chrome-har-capturer download the HAR? When bandwidth is limited to different rates some packets would be dropped so how would this effect the download of HAR?

**Comment by ivan** [comment]
HTTP runs over TCP, which ensures reliable delivery even in the presence of dropped packets.  Limiting bandwidth/dropping packets should just slow down the transfer.  There is an overview of this at https://en.wikipedia.org/wiki/Packet_loss#Packet_recovery_for_reliable_delivery

**Comment by cyrus-and** [comment]
@SivaKesava1 the HAR is generated using the timings as seen by Chrome so if it experiences bandwidth throttling, increased latency or packet loss then the generated HAR would reflect that. Conversely, if such network shaping happens *between* this module and Chrome **only** then the HAR will be unaffected.

Usually, this module communicates with Chrome using the loopback interface (`lo`), whereas Chrome accesses web sites using another interface (say, `eth0`), if that's the case you can safely enable network shaping for the latter only to achieve what you want.

Hope this helps.
