### ISSUE TITLE
Capturing Har with content

### ISSUE THREAD

**Issue by laurelrr** [cyrus-and/chrome-har-capturer#40]
It looks like I should be able to capture har with content in the current build the same way as I might use Tools->Developer tools->Save as HAR with content.  Is this correct?
However, my recorded HAR files do not have a "text" field appearing in the entries.response structure as they do when I manually save as HAR with content.   (Note: it is not a blank field, it is completely missing.)

Previously, I had Node.js version (v6.9.4 for Windows) installed but I updated to the latest version (v6.10.0) and this update did not fix the issue. 
I run chrome-har-capturer as follows from the (cmd) terminal:
> start chrome --remote-debugging-port=9222 --enable-benchmarking --enable-net-benchmarking
> chrome-har-capturer -d 10000 -o test.har http:\\www.google.com

Thanks!

**Comment by cyrus-and** [comment]
Capturing the content is optional, you have to use the ` -c, --content ` option in order to enable it.
