### ISSUE TITLE
No Cookie HTTP Header

### ISSUE THREAD

**Issue by marty90** [cyrus-and/chrome-har-capturer#44]
Hi,
I can't see any cookie related header in HTTP responses/request (for example Set-Cookie in responses).
In older versions of chrome-har-capturer I could.

**Comment by marty90** [comment]
Debugging with wscat I noticed that cookies are not sent by Chrome

**Comment by cyrus-and** [comment]
Possibly related to [this] issue.

[this]: https://bugs.chromium.org/p/chromium/issues/detail?id=692090

**Comment by marty90** [comment]
Is there any workaround?
I noticed that chrome-har-capturer doesn't operate with non-headless chrome.

Last option: use older version of chrome-har-capturer

**Comment by cyrus-and** [comment]
> Last option: use older version of chrome-har-capturer

I'm afraid that's the one... look, in principle I could make it work also with non-headless Chrome but then I could not use browser contexts and that would led me to reimplement ugly hacks such as injecting a cleanup script before each page load etc.

I'm confident that the headless mode will eventually be relatively bug-free and the de facto standard for this kind of automation.

After all using the old version should not be a problem for you, the API is different but it's so tiny that migrating back and forth should be painless while if you're just using the CLI then it's even easier.

**Comment by marty90** [comment]
Thank You,
let's hope they fix this issue!

**Comment by marty90** [comment]
For anyone interested, a workaround is to call the method Network.getAllCookies of Chrome DevTools Protocol that returns the cookie database of the browser.

**Comment by cyrus-and** [comment]
I'm closing this as it's clearly a bug with Chrome. For those who are affected I suggest to star and follow the aforementioned [upstream issue](https://bugs.chromium.org/p/chromium/issues/detail?id=692090).

**Comment by cyrus-and** [comment]
FYI apparently [fixed](https://bugs.chromium.org/p/chromium/issues/detail?id=692090#c11).
