### ISSUE TITLE
from-log release date?

### ISSUE THREAD

**Issue by Everettss** [cyrus-and/chrome-har-capturer#56]
Are there are any plans for merging from-log branch to master an release to npm? 
Capabilities of fromLog are a great connection for gathering HAR with Puppeteer.

**Comment by cyrus-and** [comment]
A couple of people manifested interest in that feature but then disappeared. In the original use case there was a Lighthouse custom audit that generated said log, what's your use case exactly?

The merging should be quite straightforward (just a few conflicts to be resolved). There was a minor issue / hackish solution concerning the creation of HAR files with content (see [here][1]). Feel free to share you thoughts about it.

[1]: https://github.com/cyrus-and/chrome-har-capturer/blob/779904d671d8a4ca494cc229290b9d3c4745d272/README.md#fromlogurl-log-options

**Comment by Everettss** [comment]
I met often question how to download [HAR file with Puppeteer](https://github.com/GoogleChrome/puppeteer/issues/30). I've investigated alternative other library solution and this branch looks promising. I finally decide to use [chrome-har](https://www.npmjs.com/package/chrome-har) (capabilities are very similar in this package). [Here](https://michaljanaszek.com/blog/generate-har-with-puppeteer) is an example where I was using this HAR generation.

**Comment by cyrus-and** [comment]
I see, what do you think about the proposed solution to generate HAR with contents? Do you think it's feasible to insert synthetic `Network.getResponseBody ` events with Puppeteer?

**Comment by cyrus-and** [comment]
Apparently, yet another person lost interest in this feature... I'll go on and merge it never the less.
