### ISSUE TITLE
Is the cache cleaned for each visit?

### ISSUE THREAD

**Issue by marty90** [cyrus-and/chrome-har-capturer#57]
Ciao!

I've a quick question.
If I run multiple times chrome-har-capturer without quitting Chrome between one visit and another, is the cache/profile cleaned?
In other words, does each visit use a clean Chrome profile?

Thank You
Martino

**Comment by cyrus-and** [comment]
It does not use a clean Chrome profile, in fact it uses whatever you provide since Chrome must be already started in order to run `chrome-har-capturer`.

But each URL is loaded in its own [browser context][1]:

> Similar to an incognito profile but you can have more than one.

Thus both data and DNS (hopefully) caches should be flushed every time.

[1]: https://chromedevtools.github.io/devtools-protocol/tot/Target#method-createBrowserContext

**Comment by marty90** [comment]
Thank you for the quick answer.
Is there a workaround to prevent this behavior?
E.g., simulate a "second visit" of a web page, where most objects are already in the browser cache.

**Comment by cyrus-and** [comment]
I could add an option to use a single context across all the page loads, what do you think?

**Comment by cyrus-and** [comment]
It should work, give it a spin.

**Comment by marty90** [comment]
Cool! It appears to work!
Unfortunately the HAR file reports the entry also for objects coming from the cache.
In other words, objects are correctly cached, but the HAR reports them. And it is impossible to distinguish an object coming from the network or from the cache. (I only noticed that the `Date` HTTP response header is some minutes before the visit to the page, and, thus, was for sure coming from cache)

However, I think it would be easy to implement as the `Response` struct from Chrome has a `fromDiskCache` boolean field.
One could add this information in the `cache` field of the HAR entry, or create a new `_fromDiskCache`.

**Comment by cyrus-and** [comment]
Yes of course! I thought I added such commit instead I just stashed the change for whatever reason...

**Comment by marty90** [comment]
It works perfectly :)
Thank you !
