### ISSUE TITLE
Unable to capturer Video request in HAR, as compare to Chrome network tab HAR

### ISSUE THREAD

**Issue by haris-rizwan** [cyrus-and/chrome-har-capturer#58]
Im trying to write a performance and networking QA script that would capture the HAR/network traffic of a given url.For this Im using chromeHar capturer module of on NodeJS.

The issue having is that if there is a video on a page its not showing it in the HAR, because of that it is impossible to get the actual weight of the page. For which im trying to write the script.

I created a sample page with just one video playing. If i checked the networks tab in chrome it shows me 4 request and the size of total page is 3.2 MB. see the screenshot below.

<img width="1244" alt="chromenetworktab" src="https://user-images.githubusercontent.com/27748909/39001624-b76a3aac-43c4-11e8-87f6-8b75f70cd5b1.png">

If i use the chromeHAR module and run the script the HAR that I get is totally different.

Please see the screenshot

<img width="1187" alt="chromehar" src="https://user-images.githubusercontent.com/27748909/39001665-d0eff53e-43c4-11e8-8b6b-f3deaf200487.png">

Even if i use timeOut argument to give a time out or use content:true . this is not working. 

```js
function getData(link) {

return new Promise(function (res, rej) {
    harCapturing.run(link,{timeout:15000}).on('har', function (har) {
        var logs = har;
        fs.writeFileSync('/Users/harisrizwan/Desktop/out.har', JSON.stringify(har))
        // console.log(logs); 
        var filteredLogs = logs.log.entries;
        fs.writeFileSync('out.json', JSON.stringify(har, null, 2));
        console.log(filteredLogs);
        res(filteredLogs);
    });
});
```

**Comment by cyrus-and** [comment]
You need to use the `-g,--grace` option of the command line utility or implement something [similar][1] if you plan to use it as a library. The timeout is the maximum allowed time to load a page before giving up.

Also please note that if the video does not auto-play, the browser will only buffer the first part.

Hope it helps.

[1]: https://github.com/cyrus-and/chrome-har-capturer/blob/bdc214b7ff4f228f036b983155828d82400e684a/bin/cli.js#L91-L96

**Comment by haris-rizwan** [comment]
@cyrus-and Thank you the grace thing worked from command line perfectly , trying to write something so it can be used as library.
