### ISSUE TITLE
Cache 304 Not Modified possible with second load?

### ISSUE THREAD

**Issue by petericebear** [cyrus-and/chrome-har-capturer#62]
Hi,

i am trying to leverage browser cache foe a second load off the page.
Is that possible?

I tried:
xargs chrome-har-capturer -k -o output.har < urls.txt

When I view the HAR file, I don't see 304 Not Modified in the results. But when I load in the browser and look in the "Network" tab, then it works good.

Any idea's?

NB: urls.txt only conatins the same url twice.

**Comment by cyrus-and** [comment]
How come that you didn't receive the <code>unknown option `-k'</code> error then?

**Comment by petericebear** [comment]
I do not know. I just installed it and tried several options out

**Comment by cyrus-and** [comment]
I mean it might not be that problem then, are you sure that with the version from master you get 304s as expected?

**Comment by petericebear** [comment]
I just copied the changes to the files on my drive from that commit. Unfortunatly still only status 200 status codes from the images.

**Comment by petericebear** [comment]
Hmm, wait a bit:
https://www.texel.net/nl/accommodaties/vakantiehuisje

I see also a status 200 in the browser itself but it shows: 200 (from memory cache) in the network tab.

**Comment by cyrus-and** [comment]
Look at this:

```console
$ node bin/cli.js -k https://cardaci.xyz https://cardaci.xyz | grep _fromDiskCache
- https://cardaci.xyz/ ✓
- https://cardaci.xyz/ ✓
                "_fromDiskCache": false,
                "_fromDiskCache": false,
                "_fromDiskCache": false,
                "_fromDiskCache": false,
                "_fromDiskCache": false,
                "_fromDiskCache": false,
                "_fromDiskCache": true,
                "_fromDiskCache": true,
                "_fromDiskCache": true,
                "_fromDiskCache": true,
                "_fromDiskCache": true,
                "_fromDiskCache": true,
```

**Comment by petericebear** [comment]
mbp-peter:chrome-har-capturer peter$ node bin/cli.js -k https://cardaci.xyz https://cardaci.xyz | grep _fromDiskCache
- https://cardaci.xyz/ ✓
- https://cardaci.xyz/ ✓

**Comment by petericebear** [comment]
I am trying this on my OSX, latest node version: v8.11.2, chrome version 67.0.3396.62 (Officiële build) (64-bits)

**Comment by cyrus-and** [comment]
`_fromDiskCache` disk cache must be present (either `true` or `false`), are you sure that you're using the latest version? Try a `git pull`.

**Comment by petericebear** [comment]
Ah yes was an old version. Now it works.
Is it possible to remove the cache after firing the script twice? I mean clean the cache in the Chrome?

If I now run the script 2 times after it, then the first request is also with the cache

**Comment by cyrus-and** [comment]
Great! Bumping the new version...

If you need "advanced" features you can always use this as a library and perform the  desired initialization yourself using [chrome-remote-interface][1] which is a dependency anyway.

[1]: https://github.com/cyrus-and/chrome-remote-interface

Otherwise just run:

```console
$ chrome-remote-interface inspect <<<'Network.clearBrowserCache()'
```

**Comment by cyrus-and** [comment]
> Bumping the new version...

[v0.13.0](https://github.com/cyrus-and/chrome-har-capturer/releases/tag/v0.13.0)
