### ISSUE TITLE
Android connection has working socket, but gives 'Not supported' message

### ISSUE THREAD

**Issue by fafnirbcrow** [cyrus-and/chrome-har-capturer#63]
| Component | Version
|-|-
| Operating system	  	 	| OSx/Linux
| Node.js					| c8.9.4
| Chrome/Chromium/...		| Android 67.0.3396.81
| chrome-remote-interface	| 0.25.6

Is Chrome running in a container? NO

So having a issue similar to https://github.com/cyrus-and/chrome-remote-interface/issues/332 and am able to get past the socket hang up/protocol local issue. 

Once through that however, I am getting 'Not supported' as an error message, and the program does not exit.

I am using the force option on the run also, as thinking that may be related, but it did not solve the problem.

For my command line run, I just simplified the CLI version a hair, attached below

```
let url = ['https://github.com'];


let host = 'localhost';
let port = 9222;
let parallel = false;
let force = true;

H.run(url, {
    host, port, force
}).on('load', (url) => {
    console.log(`- ${prettify(url)} `);
    if (parallel) {
        log('…\n');
    }
}).on('done', (url) => {
    if (parallel) {
        console.log(`- ${prettify(url)} `);
    }
    log('✓\n');
}).on('fail', (url, err) => {
    if (parallel) {
        console.log(`- ${prettify(url)} `);
    }
    console.log(`✗\n  ${err.message}\n`);
}).on('har', (har) => {
    //const fs = require('fs');
    const json = JSON.stringify(har, null, 4);
    /*const output = program.output
        ? fs.createWriteStream(program.output)
        : process.stdout;
    output.write(json);
    output.write('\n');*/
    console.log(json);
    console.log('\n');
});
```

**Comment by cyrus-and** [comment]
Eh... they have apparently killed [`Target.createBrowserContext`][1] on Android and the reason escapes me.

You can workaround by passing the `-k, --cache` option but you won't have the usual cache/dns isolation.

[1]: https://chromedevtools.github.io/devtools-protocol/tot/Target#method-createBrowserContext

**Comment by cyrus-and** [comment]
Asked in the [Google Group][1].

[1]: https://groups.google.com/forum/#!topic/chrome-debugging-protocol/1CvAR0roSA0

**Comment by cyrus-and** [comment]
I'm quoting the reply from the Google Group:

> `Target.createBrowserContext` has been implemented in headless embedder for a while. However, headful implementation was added only in Chrome 68: https://crrev.com/553323

**Comment by cyrus-and** [comment]
> Eh... they have apparently killed Target.createBrowserContext on Android and the reason escapes me.

This is wrong.
