### ISSUE TITLE
Error: socket hang up 

### ISSUE THREAD

**Issue by jsw-zorro** [cyrus-and/chrome-har-capturer#85]
I tried to use this tool to save the HAR file in an Android Chrome. I follow these steps:
* First, start the chrome from my Android Device.
* Set `adb forward tcp:9222 localabstract:chrome_devtools_remote` on my computer.
* chrome-har-capturer -f -p 9222 -o m.har https://www.google.com
After I finish these commands, I received the `socket hang up` information.

Do you have any ideas, which step I should add to save the HAR files from the Android Device?

**Comment by cyrus-and** [comment]
Maybe #63?

**Comment by jsw-zorro** [comment]
I just tried with -k option. But still nothing happens. The error shows `socket hang up`.

**Comment by jsw-zorro** [comment]
Also after I set the adb forward, I try with `curl http://localhost:9222/json/protocol` But there is no response. Do you have any idea on what's happening?

**Comment by cyrus-and** [comment]
Give it a try, it should work now.

> Do you have any idea on what's happening?

Yeah, there is no protocol descriptor in Chrome for Android ("to save space"...).

**Comment by jsw-zorro** [comment]
> Give it a try, it should work now.
> 
> > Do you have any idea on what's happening?
> 
> Yeah, there is no protocol descriptor in Chrome for Android ("to save space"...).

It now shows failed to create browser context.

**Comment by cyrus-and** [comment]
You have to use `-k`, see #63.

**Comment by jsw-zorro** [comment]
I see. It works now! Thanks!
