### ISSUE TITLE
Methdology question

### ISSUE THREAD

**Issue by jsw-zorro** [cyrus-and/chrome-har-capturer#87]
For some website, for example, the CNN. It keeps refreshing, what's this tool's methodology to decide when to finish?

**Comment by cyrus-and** [comment]
It waits `-g, --grace <ms>` (default 0) after:

https://github.com/cyrus-and/chrome-har-capturer/blob/57e5cbbde764eadb62038735a189cb6a2d6a9287/lib/stats.js#L24-L33

So basically all the following events must happen:

- the initial request must have received a response;
- [`Page.loadEventFired`](https://chromedevtools.github.io/devtools-protocol/tot/Page/#event-loadEventFired);
- [`Page.domContentEventFired`](https://chromedevtools.github.io/devtools-protocol/tot/Page/#event-domContentEventFired).

**Comment by jsw-zorro** [comment]
Thanks, get it!
