### ISSUE TITLE
Question: How to redirect the success/fail output to a file?

### ISSUE THREAD

**Issue by jsw-zorro** [cyrus-and/chrome-har-capturer#88]
I want to redirect the output like: `- https://baidu.com/ ✓` to redirect to a file. Using 
`chrome-har-capturer -f -k -p 9222 -o test.har $url | tee -a "./test.log"`
However, it seems the output will always be null. Is there anyway I can redirect the specific successful or failed information?
Thanks for all the help.

**Comment by cyrus-and** [comment]
You want to redirect the standard error:

```sh
chrome-har-capturer -f -k -p 9222 -o test.har "$url" 2>>test.log
```

**Comment by jsw-zorro** [comment]
Thanks, previously I made a mistake in the standard error redirection and typed it wrong. So I mistakenly considered it will also not works. Thx!
