### ISSUE TITLE
Missing favicon entry

### ISSUE THREAD

**Issue by noleakseu** [cyrus-and/chrome-har-capturer#90]
Reproduction:
```
$ google-chrome --remote-debugging-port=9222 --disable-extensions
$ chrome-har-capturer -o capturer.har -c https://noleaks.eu
```
Expectation: capturer.har must include 7th entry https://noleaks.eu/assets/favicon.ico.

PuppeteerHar and HarRecorder have the same issue in headless mode.
Nonetheless, chrome-har-capturer is the most accurate tool for HAR dumps at the moment. Thank you!

**Comment by cyrus-and** [comment]
> Nonetheless, chrome-har-capturer is the most accurate tool for HAR dumps at the moment. Thank you!

Glad to hear that! :)

I think there are two issues here:
- the favicon is not loaded in headless mode (apparently?);
- the favicon is requested lazily (i.e., after the page load event).

So start Chromium in regular mode (no `--headless`), then add some grace time:

```console
$ chrome-har-capturer -o capturer.har -c https://noleaks.eu -g 1000
- https://noleaks.eu/ ✓

$ gron capturer.har | grep request.url
json.log.entries[0].request.url = "https://noleaks.eu/";
json.log.entries[1].request.url = "https://noleaks.eu/assets/bootstrap.min.css";
json.log.entries[2].request.url = "https://noleaks.eu/assets/on-512.svg";
json.log.entries[3].request.url = "https://noleaks.eu/assets/chrome.svg";
json.log.entries[4].request.url = "https://noleaks.eu/assets/firefox.svg";
json.log.entries[5].request.url = "https://noleaks.eu/assets/opera.svg";
json.log.entries[6].request.url = "https://noleaks.eu/assets/favicon.ico";
```
